### ISSUE TITLE
Clean up destinations page

### ISSUE THREAD

**Issue by kristjanjansen** [tripikad/trip2#702]
#### Continent

Instead of stats we show a custom textual introduction about the continent (see #722)

#### Country, City

Stats is available as ```config("destinations.$destination_id")``` (see #711)

```php
725 => [
  'code' => 'AF',
  'capital' => 'Kabul',
  'area' => 652230,
  'population' => '29121286', # Divide by 1000000 and round this
  'callingCode' => '93',
  'currencyCode' => 'AFN',
],
```

Display:

```yaml
Afganistan:

Suurus: 652230 m²
Rahvaarv: 29 miljonit
Helistamiskood: +93
Valuuta: AFN
```

### Map

* Hide ```c-map__location```

### Forum / Tripikad räägivad

* Make link to point to Üldfoorum, with proper destination filter selected

### Blogs

Hide blogs block
